config/routes.rb
Rails.application.routes.draw do
  get 'pixels/create'

  get 'pixels/update'

  resources :providers
  root :to => 'welcome#index'
  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'sign_in',
               sign_out: 'sign_out',
             },
             controllers: {
               sessions: 'sessions',
             }

  post '/pixel/', to: 'pixels#create', as: 'pixel_create'
  post '/pixel/:name', to: 'pixels#update', as: 'pixel_update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jwt_blacklist.rb
class JWTBlacklist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Blacklist

  self.table_name = 'jwt_blacklist'
end

app/models/pixel.rb
class Pixel < ApplicationRecord
  belongs_to :provider
  validates :provider, presence: true
  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 100 }

  before_validation :convert_name_without_space

  def convert_name_without_space
    self.name = self.name.gsub(" ","")
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :pixel, dependent: :destroy
  validates :name, presence: true, length: { minimum: 1, maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JWTBlacklist

  validates :email, uniqueness: true, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, length: { maximum: 254 }
end

app/controllers/api_controller.rb
#This class is the parent for the actions for API Rest
class ApiController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    render json: {
      body: 'RecordNotFound'
    }, status: 404
  end
 
  #Render JSON with response for a single object
  def render_resource(resource)
    if resource.errors.empty?
      render json: resource
    else
      validation_error(resource)
    end
  end

  #Format for errors validations
  def validation_error(resource)
    render json: {
      errors: [
        {
          status: '400',
          title: 'Bad Request',
          detail: resource.errors,
          code: '100'
        }
      ]
    }, status: :bad_request
  end

  def authenticate_user_api!
    unless current_user
      render :json => {'error' => 'authentication error'}, :status => 401
    end
  end
end

app/controllers/application_controller.rb
#This class is the parent for actions in browser
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pixels_controller.rb
class PixelsController < ApiController
  before_action :authenticate_user_api!
  before_action :set_pixel, only: [:update]

  #post '/pixel/'
  #Create new pixel
  def create
    @pixel = Pixel.new
    @pixel.assign_attributes(pixel_params)
    @pixel.save
    render_resource(@pixel)
  end

  #post '/pixel/name'
  #Increments one the conversion value
  def update
    @pixel.conversions += 1
    @pixel.save
    render_resource(@pixel)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pixel
      @pixel = Pixel.find_by!(name: params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pixel_params
      params.require(:pixel).permit(:name, :provider_id)
    end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /providers/1
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /providers/1
  def destroy
    @id = @provider.id
    @provider.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  skip_before_action :verify_authenticity_token, only: [:create, :destroy]

  private

  def respond_with(resource, _opts = {})
    if request.headers["CONTENT_TYPE"]=='application/json'
      render json: resource
    else
      super
    end
  end

  def respond_to_on_destroy
    if request.headers["CONTENT_TYPE"]=='application/json'
      head :no_content
    else
      super
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #Main page
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pixels_helper.rb
module PixelsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/top_menu" %>
    <%= yield %>
  </body>
</html>

app/views/pixels/create.html.erb
<h1>Pixels#create</h1>
<p>Find me in app/views/pixels/create.html.erb</p>

app/views/pixels/update.html.erb
<h1>Pixels#update</h1>
<p>Find me in app/views/pixels/update.html.erb</p>

app/views/providers/_form.html.erb
<%= form_for(provider) do |f| %>
  <% if provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr id="provider-<%= provider.id %>">
        <td><%= provider.name %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/providers/destroy.js.erb
$("#provider-<%= @id %>").fadeOut();

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Providers</h1>

<div id="providers-list">
  <%= render "list" %>
</div>

<br>

<%= link_to 'New Provider', new_provider_path, class: "btn grey" %>

app/views/providers/new.html.erb
<div class="form-object">

  <h1>New Provider</h1>

  <%= render 'form', provider: @provider %>

  <%= link_to 'Back', providers_path %>

</div>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>
<% if @provider.pixel.present? %>
  <hr>
  <h4>Pixels assigned to this provider:</h4>
  <% @provider.pixel.each do |pixel| %>
    <p>
      <li>Name píxel: <%= pixel.name %> / Conversions: <%= pixel.conversions %></li>
    </p>
  <% end %>
<% end %>


<%= link_to 'Edit', edit_provider_path(@provider), class: "btn grey" %> |
<%= link_to 'Back', providers_path, class: "btn grey" %>

app/views/shared/_top_menu.html.erb
<nav class="topmenu">
  <% if current_user.present? %>
      <%= link_to "Providers", providers_path, class: "menu-link btn white" %>
      <%= link_to t("default.logout"), destroy_user_session_url, method: :delete, class: "btn white" %>
  <% else %>
    <%= link_to t("default.login"), new_user_session_path, class: "btn white" %>
  <% end %>
</nav>

app/views/welcome/index.html.erb
<h1>Bienvenido a tracking management</h1>